#ifndef CORETYPES_H_INCLUDED
#define CORETYPES_H_INCLUDED


typedef enum {
	CORE_OK,
	CORE_READ_ONLY,
	CORE_ILLEGAL_INSTRUCTION,
	CORE_MEMORY_UNINITIALIZED
} CORE_STATUS;
typedef enum {
	DATA_ACCESS_PAGE0,
	DATA_ACCESS_DSR
} DATA_ACCESS_PAGE;

#endif
