#ifndef MEMTYPES_H_INCLUDED
#define MEMTYPES_H_INCLUDED


typedef enum {
	MEMORY_OK,
	MEMORY_UNINITIALIZED,
	MEMORY_ALLOCATION_FAILED,
	MEMORY_ROM_MISSING,
	MEMORY_SAVING_FAILED,
	MEMORY_UNMAPPED,
	MEMORY_ROM_WINDOW,
	MEMORY_MIRROWED_BANK,
	MEMORY_UNALIGNED,
	MEMORY_READ_ONLY
} MEMORY_STATUS;


#endif
